name: pytorchrl
channels:
    - https://conda.anaconda.org/soumith
    - https://conda.anaconda.org/kne
    - https://conda.anaconda.org/tlatorre
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
dependencies:
    - python==3.5.3
    - scipy
    - mako
    - path.py
    - pybox2d
    - pygame
    - joblib==0.10.3
    - pip:
        - http://download.pytorch.org/whl/torch-0.3.0.post4-cp35-cp35m-macosx_10_6_x86_64.whl 
        - torchvision
        - numpy==1.13.1
        - gym==0.9.2
        - matplotlib==2.0.2
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - cached_property
        - pyprind
        - boto3
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/rll/rllab.git
        - cloudpickle
